apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "18.4.2"
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: logging
  values:
    deploymentMode: Monolithic

    loki:
      useTestSchema: true
      storage:
        type: filesystem
      auth_enabled: false
      commonConfig:
        replication_factor: 1

    singleBinary:
      replicas: 1
      resources:
        requests: { cpu: 100m, memory: 256Mi }
        limits: { cpu: 500m, memory: 512Mi }
      persistence:
        enabled: true
        size: 5Gi
        storageClass: local-path

    resultsCache:
      enabled: false
    chunksCache:
      enabled: false

    write:
      replicas: 0
      enabled: false
    read:
      replicas: 0
      enabled: false
    backend:
      replicas: 0
      enabled: false

    # Trim extras we don't need for a single-node lab
    gateway:
      enabled: false
    test:
      enabled: false
    lokiCanary:
      enabled: false
    minio:
      enabled: false
